### ISSUE TITLE
Cli does not respect parameters when creating a trigger with a feed.

### ISSUE THREAD

**Issue by style95** [apache/incubator-openwhisk-client-go#122]
It seems Cli does not response `param` field when creating a trigger with a feed.
```
$ wsk trigger create everyhour --feed /whisk.system/alarms/alarm --param cron  "*/10 * * * *" --param name "hello"
```

There is no default parameters configured in my trigger.

**Comment by mdeuser** [comment]
possible duplicate of https://github.com/apache/incubator-openwhisk-cli/issues/293

**Comment by style95** [comment]
ok, it seems it comes from the fundamental issue between trigger parameters and feed parameters.

closing as it is duplicate.
