### ISSUE TITLE
Example is broken: whisk.NewClient(http.DefaultClient, nil)

### ISSUE THREAD

**Issue by tleyden** [apache/incubator-openwhisk-client-go#22]
From the README example:

```
client, _ := whisk.NewClient(http.DefaultClient, nil)
action, resp, err := client.Actions.List("hello")
```

But this breaks, since inside the `NewClient()` code it calls `if config.Insecure {..}` on a nil config, which panics with `panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by houshengbo** [comment]
@tleyden I have resolved this issue. Please verify. 
If it still exists, feel free to reopen it.
