### ISSUE TITLE
Update doc to remove experimental references

### ISSUE THREAD

**Issue by dubee** [apache/incubator-openwhisk-client-go#48]
The Disclaimer (https://github.com/apache/incubator-openwhisk-client-go#disclaimer) section in README.md needs to be updated to remove the experimental references as this repo is no longer experimental. Also, the source code synchronize references need to be removed.

**Comment by mrutkows** [comment]
Fixed: https://github.com/apache/incubator-openwhisk-client-go/issues/82
PR: https://github.com/apache/incubator-openwhisk-client-go/pull/86
