### ISSUE TITLE
Preserve Git History from OpenWhisk

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk-client-go#8]
It looks like the go-whisk files were copied and pushed to this repo. Please keep intact the git history of go-whick from OpenWhisk. @csantanapr, @houshengbo, @pritidesai

**Comment by dubeejw** [comment]
Also, I don't know if this repo is appropriately named.

**Comment by pritidesai** [comment]
Yup, I agree about preserving history, I don't have admin access and I believe (not a git expert) I can not do that without one:

https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

I will look into it more.

**Comment by csantanapr** [comment]
Since there is no active development on master branch it should be ok to rewrite history on master to preserve the history from main repo. 

Please ask @rabbah for assistance when needing a rewrite with admin access

Also the name of the repoits trying to have a convention with other languages for client side code/lib 
openwhisk-client-js
openwhisk-client-python
openwhisk-client-java
openwhisk-client-go

**Comment by mrutkows** [comment]
Fixed title typo ;)

**Comment by pritidesai** [comment]
This can not be done through PR and don't have write access on master branch, I tried these steps:

```
git clone https://github.com/openwhisk/openwhisk.git
cd openwhisk
git filter-branch --prune-empty --subdirectory-filter tools/cli/go-whisk master
git remote set-url origin https://github.com/pritidesai/openwhisk-client-go.git
git push origin client-go
```
Can not create pull request:
https://github.com/openwhisk/openwhisk-client-go/compare/master...pritidesai:client-go?expand=1

**There isn’t anything to compare.
openwhisk:master and pritidesai:client-go are entirely different commit histories.**

@rabbah please help.

**Comment by paulcastro** [comment]
@pritidesai check with @dubeejw , he has some scripts to prune a repo and preserve history.

**Comment by rabbah** [comment]
See https://github.com/openwhisk/openwhisk-cli/issues/6#issuecomment-296444068

**Comment by dubeejw** [comment]
@csantanapr, @houshengbo, it looks like Paul has made some commits that copied history to the CLI repos resulting in all of the history not being preserved. I'm assuming these commits have to be removed in order to get all of the history.

**Comment by dubeejw** [comment]
For instance this commits adds the api.go file from @mdeuser, but does not preserve the history from him. https://github.com/openwhisk/openwhisk-client-go/commit/277d1e8fb63dc8f6cf25a47346f363d5ff7a359d

**Comment by houshengbo** [comment]
@dubeejw I have rebase with all the commits except the unexpected commits in another repo: https://github.com/houshengbo/incubator-openwhisk-client-go-backup, branch: latest. I also removed some other commits, which only did the content copying of the legacy repos. If you think this is something we can accept, we can port them into this repo. Thx.

**Comment by csantanapr** [comment]
Is great to get the history from the start from @theophoric

@houshengbo 
I compared the two branches, only things I found differences are
1. whisk/api.go
```
```230c231
<     apiArray := new(ApiListResponse)
---
>     apiArray := new(RetApiArray)
265c266
<     retApi := new(ApiCreateResponse)
---
>     retApi := new(RetApi)
300c301
<     retApi := new(ApiGetResponse)
---
>     retApi := new(RetApiArray)
489c490
<     retApi := new(ApiDeleteResponse)
---
>     retApi := new(RetApi)```
```

2. A new file on the client-go-backup-latest not present in main repo `whisk18n/i18n_resources.go`

Other than that is normal Apache header, and the relative reference `../whisk18n`

**Comment by houshengbo** [comment]
@csantanapr 
This file whisk18n/i18n_resources.go is what need to have in this repo. If not, the developer/user has to build this resource first by go-bindata each time before building the binaries. OpenWhisk does it automatically in the docker, but we need to prepare this file in the new repo, so that we do not need an additional build before binaries.

Apache header is definitely what we need to have, and the relative reference also changed into absolute path based on the standard structure of a go project.

**Comment by csantanapr** [comment]
Thanks Vincent so the only remaining issue is why the differences in api.go doesn't match

**Comment by houshengbo** [comment]
@csantanapr @dubeejw @mdeuser 
I have fixed the issue of mismatch in api.go at https://github.com/houshengbo/incubator-openwhisk-client-go-backup/commits/latest. Please help me verify if it is OK.

**Comment by csantanapr** [comment]
I worked with @houshengbo today and were able to merge the correct history to master branch

So anyone that has a copy of master branch sorry this had to be a force push

**Comment by csantanapr** [comment]
Closing as this is resolved now
